### ISSUE TITLE
Linking fails: unresolved external symbol _clRelease...

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperantoj_prototype#1]
Hi Stephane @StRigaud ,

I think I'm almost there and can compile a first Java Wrapper around CLIc. I'm currently hitting a linker error. When running `mvn` from the Visual Studio Terminal, I reveive some warnings and eventually this linker error:

```
Microsoft (R) Incremental Linker Version 14.29.30136.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:jniclesperanto.dll
/ltcg
/dll
/implib:jniclesperanto.lib
/OUT:jniclesperanto.dll
/LIBPATH:C:\structure\code\clesperantoj_prototype\native\lib\
"/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib\x64\"
OpenCL.lib
CLIc.lib
psapi.lib
jniclesperanto.obj
   Creating library jniclesperanto.lib and object jniclesperanto.exp
jniclesperanto.obj : error LNK2001: unresolved external symbol _clReleaseCommandQueue@4
jniclesperanto.obj : error LNK2001: unresolved external symbol _clReleaseContext@4
jniclesperanto.obj : error LNK2001: unresolved external symbol _clReleaseDevice@4
jniclesperanto.dll : fatal error LNK1120: 3 unresolved externals
```

I assume, I'm forgetting some library to link to. Do you have an idea which? I'm already linking `CLIc` and `OpenCL` (lib files on Windows): https://github.com/clEsperanto/clesperantoj_prototype/blob/b57560011a3c7ee2a5be5709a4a77f0708cf7fc6/src/main/java/net/clesperanto/clicwrapper/clesperanto.java#L14

Any hint is welcome!

Best,
Robert

**Comment by StRigaud** [comment]
No other dependency are needed.
The linking error is related to OpenCL so i would guess something wrong happened there.

Possibility:

1. issue between the opencl-headers, opencl-clhpp, and the OpenCL lib from Nvidia.
2. Version of OpenCL (that would be a first, hence i doubt it).
3. something else we haven't figured out yet.
4. both point 1 and 2 at the same time.

A quick search on [stackoverflow](https://stackoverflow.com/questions/15855759/opencl-1-2-c-wrapper-undefined-reference-to-clreleasedevice). I don't know if its the solution but sound familliar.

This confort me in the need to use the ICD-loader for CLIc.
