### ISSUE TITLE
Tag in CLiC missing

### ISSUE THREAD

**Issue by stefanhahmann** [clEsperanto/clesperantoj_prototype#14]
While trying to build using https://github.com/clEsperanto/clesperantoj_prototype/blob/main/guideline.md
the following error came up:

![grafik](https://user-images.githubusercontent.com/10515534/227498758-864d8890-ea4f-4be3-bf18-ae15d21fcfc6.png)

It seems that the tag which is trying to be checked out, does not actually exist: https://github.com/clEsperanto/CLIc_prototype/tags

Should the tag 'std-flag-compatibility' be replaced with the latest available flag, i.e. '0.6.3'?

**Comment by stefanhahmann** [comment]
I just tried to change the tag to '0.6.3'.

The error described above then disappears, however, then a new error comes up:
![grafik](https://user-images.githubusercontent.com/10515534/227501282-493dabc1-e2b7-4229-890d-80417950a479.png)

**Comment by StRigaud** [comment]
Ha yes, sorry. This was while we were still trying to make it work.
We need to tell CMake to clone the master branch for now, until I publish a new version of CLIc.

https://github.com/clEsperanto/clesperantoj_prototype/blob/53d058c50835dad73483e93b80f89961f01dfcb5/native/clesperantoj/CMakeLists.txt#L24-L28

We simply need to replace  my `master`. I will push a quick fix for this!
