### ISSUE TITLE
Test package does not exist

### ISSUE THREAD

**Issue by stefanhahmann** [clEsperanto/clesperantoj_prototype#16]
After successfully building the project, the readme.md suggests to run a test with these files:

https://github.com/clEsperanto/clesperantoj_prototype/tree/main/src/main/java/net/clesperanto/test

However, the package does not exist anymore.

**Comment by StRigaud** [comment]
Nope, I have removed it. 

I test it by running the `ClesperantoJ.java` code in the `src/main/java/net/clesperanto` folder.

We are pretty much restarting from fresh here :upside_down_face:

**Comment by StRigaud** [comment]
Just check the code of ClesperantoJ at line 34:
https://github.com/clEsperanto/clesperantoj_prototype/blob/7cf130d225ecd57e78f4bfa32753b10c6b9e668c/src/main/java/net/clesperanto/ClesperantoJ.java#L34

I am instantiating a new processor and it may not fit with your hardware. Though I would have expect an error if selecting a wrong Processor or at least a warning.

**Comment by StRigaud** [comment]
this issue should be soved now, wrong device selection return a `cerr` and select the default available device
