### ISSUE TITLE
Evaluate Javacpp approach to wrapping Clic

### ISSUE THREAD

**Issue by bnorthan** [clEsperanto/clesperantoj_prototype#2]
See [javacpp branch](https://github.com/clEsperanto/clesperantoj_prototype/tree/javacpp)

I see 2 parts to this

1.  Evaluate if [javacpp](https://github.com/bytedeco/javacpp) an approach we want to use for cleperantoj
2.  If yes, harden the current prototype design. 

Theoretically the previous build instructions (basically start a Microsoft Visual Studio 64 bit command prompt and run mvn from parent directory) should still work... theoretically :).  Then you can run this [test class](https://github.com/clEsperanto/clesperantoj_prototype/blob/javacpp/src/main/java/net/clesperanto/clicwrapper/InteractiveWrapperTest.java). 

Anyway here is what we have so far

1. A c++ wrapper called [clesperantoj](https://github.com/clEsperanto/clesperantoj_prototype/blob/javacpp/native/clesperantoj/include/clesperantoj.h) around clesperanto.  Currently this is needed because ```clesperanto``` exposes ```Object``` and uses a few non-trivial structures and objects from the c++ standard library.  For first iteration I did not want to wrap all of this so created ```clesperantoj``` which only exposes primitive types in the interface.   As we develop this we will likely add more complexity to ```clesperantoj``` and may reach a point where the wrapping is sophisticated enough to simply wrap ```clesperanto```.  Or we may want to keep the simpler wrapper long term, to avoid more complicated java/c++ wrapping.  I'm not sure. 
2.  A java 'configuration' class called [clesperantoJ](https://github.com/clEsperanto/clesperantoj_prototype/commit/88ef3d504a2a654624e9fdbdddc8bba06f6dc33e).  This simply includes the c++ header file ```clesperantoj.h``` and adds some additional info that are needed to build templated functions.  This file will be automatically parsed by javacpp to create a java wrapper around ```clesperantoj.h```.   
3. [pom.xml](https://github.com/clEsperanto/clesperantoj_prototype/commit/c35405ab901fb5a25eff47e92f477f05c519e130) has been modified to start the cpp build script, cppbuild.sh with exec-maven-plugin,  use the build-helper-maven-plugin to add the gen source directory (which will contain the wrappers that are auto-generated by the parser), add javacpp plugin and set include and link paths., add the parse goal to the javacpp plugin to parse clesperantoj.java and add the process-classes goal to the javacpp plugin to process clesperantojWrapper to generate jni wrappers.   

Anyway, if we do decide to use javacpp, next step is to iterate on and improve this design.

**Comment by bnorthan** [comment]
I'm not knowledgeable regarding how conda-forge is used to package java applications.   Do we need to be able to build the java wrappers to Clic without using maven?

**Comment by mkitti** [comment]
Their preference is to be able to build everything from source. One could still use maven, but their preference would be to populate the dependencies via other conda-forge packages rather than having maven fetch remote dependencies.

That said, they do have maven available on conda-forge:
https://anaconda.org/conda-forge/maven

**Comment by StRigaud** [comment]
We are not commited to JavaCPP and things seems to work. closing the issue :)
