### ISSUE TITLE
Non-used parameter in cpp code

### ISSUE THREAD

**Issue by carlosuc3m** [clEsperanto/clesperantoj_prototype#35]
HEllo @StRigaud ,
I am going over the structuring of the Java code and to do so I tried to understand a little of the JAvacpp code.

I've had very limited experience with c or c++ so this might be stupid, but could we remove the argument `size` here:
https://github.com/clEsperanto/clesperantoj_prototype/blob/411a72b6c39a7f5498811ae537acc20cd6baeafd/native/clesperantoj/src/clesperantoj.cpp#L154

and on the methods below.

Sorry if the question is to naive.

Regards,
Carlos

**Comment by StRigaud** [comment]
Yes, the `size` parameter is not used here.

We could remove it, or we can also use it to make sure that the pointer size fits the ArrayJ size and that we do not mess up with the memory.

for now I think we can ignore it or remove it.

**Comment by carlosuc3m** [comment]
I was assuming that size could also be calculated from the float data argument. 

I will ignore it!

**Comment by StRigaud** [comment]
We can yes, but for example, if we know or provide a different size we can also imaging writing or reading only a sub-part of the buffer memory,

**Comment by carlosuc3m** [comment]
That is another of the things I was wondering. 
What happens when `data` is not of the same size as `array`?

I can imagine that when `data` is smaller we just copy from the beginning, but what happens when `data` is bigger?

Also if we keep `size`, should not we maybe have a `pos` parameter to know from where does the copy start?

Should we just make compulsory that the size of `array` and `data` are the same?

**Comment by StRigaud** [comment]
> What happens when data is not of the same size as array?
if it is less, it write a sub-part, it is more, it can generate a runtime error, or nothing depending on what is next to the memory buffer.

> Also if we keep size, should not we maybe have a pos parameter to know from where does the copy start?
Should we just make compulsory that the size of array and data are the same?

My idea is to do a bit similarly that the python and C++, Start basic with full read or write, and  improve the java API with more advance operation latter on when the reste is stable.

But yes, there is already some C++ method to write and read sub-part of a buffer: https://github.com/clEsperanto/CLIc/blob/39e8f92ae091ca023313e35b437061d51de89877/clic/include/array.hpp#L101-L155

I just made the basic one visible in clesperantoJ so far

**Comment by StRigaud** [comment]
I have pushed this #43 which make native Cpp read and write function work for sub-region. 

Could be interesting in future to extend the `Converters` and the Java read/write operation to allow sub-region read and write. Not directly usefull for users but could help in some optimisation as well ass tilling
