### ISSUE TITLE
Segmentation fault when working with 8-bit and 16 bit integer images

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperantoj_prototype#6]
Currently, we can only process float-type images. This can be reproduced by changing [this line](https://github.com/clEsperanto/clesperantoj_prototype/blob/d61ad99b840ce113ef1a3a5d1ed353b904ea0bf8/src/main/java/net/clesperanto/test/YetAnotherPlayground.java#L16) to
```
IJ.run(imp, "16-bit", "");
```

This commented out code section might also be helpful for debugging:

https://github.com/clEsperanto/clesperantoj_prototype/blob/d61ad99b840ce113ef1a3a5d1ed353b904ea0bf8/src/main/java/net/clesperanto/deprecated/InteractiveWrapperTest.java#L59

Before diving deeper into this, we should make sure that pushing 8-bit and 16-bit integer images works in CLIc. See also:
* https://github.com/clEsperanto/CLIc_prototype/issues/72

No hurry though. CC @StRigaud

**Comment by bnorthan** [comment]
I can replicate this error on the c++ side with a very simple test program.  Pushing a float array works for me but not a short array.   Of course, if I did something else incorrect that is causing the error let me know. 

```
void testPush(cle::Clesperanto cle) {
    std::vector<float> vecDataFloat;
    std::vector<short> vecDataShort;
    
    int rows=500;
    int cols=500;
    
    vecDataFloat.resize(rows*cols);
    vecDataShort.resize(rows*cols);

    float * vecPointerFloat = vecDataFloat.data();
    short * vecPointerShort = vecDataShort.data();

    for (int i=0;i<rows*cols;i++) {
        vecPointerFloat[i]=i;
        vecPointerShort[i]=i;
    }
    
    std::array<size_t,3> dimensions = {cols, rows, 1};
    auto inFloat = cle.Push<float>(vecDataFloat, dimensions, "image");
    auto inShort = cle.Push<short>(vecDataShort, dimensions, "image");
   
}
```

**Comment by StRigaud** [comment]
this is fixed
