### ISSUE TITLE
Tests fail when executed in parallel

### ISSUE THREAD

**Issue by carlosuc3m** [clEsperanto/clesperantoj_prototype#61]
Hello @StRigaud ,
I am working on the tests an finding that when the more than 4-5 tests are launched in parallel, there is a segmentation fault.

I don't think the GPU is running out of space because the tests create only 2x2 arrays, so I don't know what is happening.

I wil try to research more on this, I don't even know if it is reproducible in c++ or python but I just wanted to comment it to you to see if you had any idea why this is happening.
REgards,
Carlos

**Comment by carlosuc3m** [comment]
Ok it is not because they are being executed in parallel but because something happening with Icy.
I am going to keep digging on this, but Is suspect it has to do with the weird classloading system that Icy has.

**Comment by StRigaud** [comment]
idk if related but trying to build with maven in the `clij3` repo is failing with a lot of error related to Icy.

**Comment by carlosuc3m** [comment]
can you provide the errors please? @StRigaud

**Comment by StRigaud** [comment]
I have no issue with clesperantoj but this is the mvn output from trying to build clij3 ([my branch](https://github.com/clEsperanto/clij3/tree/stephane-test-new-clej)) with clesperantoJ on my local machine:


[error_mvn_build.txt](https://github.com/user-attachments/files/16836431/error_mvn_build.txt)

(the error msg is too long for github...)

**Comment by StRigaud** [comment]
For now let's remove support of Icy (we keep it into a new branch and will come back to it later on)
ToDo for @carlosuc3m
